CREATE TABLE camiseta(
    id BIGSERIAL PRIMARY KEY,
    tamanho VARCHAR(2) NOT NULL,

    id_tema BIGINT NOT NULL,

    CONSTRAINT fk_camiseta_tema FOREIGN KEY (id_tema) REFERENCES tema(id) ON DELETE RESTRICT ON UPDATE CASCADE
);